# Name : Naveen Mathews Renji | CWID : 20016323 

## Import Libraries

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

## Load the dataset

In [2]:
df = pd.read_csv("breast-cancer-wisconsin.csv")

In [3]:
df.head()

Sample  F1  F2  F3  F4  F5  F6  F7  F8  F9  Class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2

In [4]:
num_rows = df.shape[0]
print(num_rows)

699


## Taking care of missing values

In [5]:
df['F6']=df['F6'].replace('?',np.nan)
df = df.dropna()
del df['Sample']

In [6]:
df.describe()

F1          F2          F3          F4          F5          F7  \
count  683.000000  683.000000  683.000000  683.000000  683.000000  683.000000   
mean     4.442167    3.150805    3.215227    2.830161    3.234261    3.445095   
std      2.820761    3.065145    2.988581    2.864562    2.223085    2.449697   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      2.000000    1.000000    1.000000    1.000000    2.000000    2.000000   
50%      4.000000    1.000000    1.000000    1.000000    2.000000    3.000000   
75%      6.000000    5.000000    5.000000    4.000000    4.000000    5.000000   
max     10.000000   10.000000   10.000000   10.000000   10.000000   10.000000   

               F8          F9       Class  
count  683.000000  683.000000  683.000000  
mean     2.869693    1.603221    2.699854  
std      3.052666    1.732674    0.954592  
min      1.000000    1.000000    2.000000  
25%      1.000000    1.000000    2.000000  
50%      1.000000    1.000000    2.000000  
75%      4.000000    1.000000    4.000000  
max     10.000000   10.000000    4.000000

## Creating NB Model and classifying the training data

In [7]:
y=df['Class']
y=np.where(y==2,0,1)
X=df.drop('Class',axis=1).values

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)

## Guassian Naive Bayes

In [9]:
nbg = GaussianNB()
nbg.fit(X_train, y_train)
nbg.score(X_test, y_test)
Y_pred=nbg.predict(X_test)
print("The Confusion Matrix is -")
print(confusion_matrix(y_test,Y_pred))
print("The Classification Report Matrix is -")
print(classification_report(y_test,Y_pred))

The Confusion Matrix is -
[[124   6]
 [  2  73]]
The Classification Report Matrix is -
              precision    recall  f1-score   support

           0       0.98      0.95      0.97       130
           1       0.92      0.97      0.95        75

    accuracy                           0.96       205
   macro avg       0.95      0.96      0.96       205
weighted avg       0.96      0.96      0.96       205



## Bernoulli Naive Bayes

In [10]:
nbb = BernoulliNB()
nbb.fit(X_train, y_train)
nbb.score(X_test, y_test)
Y_pred=nbb.predict(X_test)
print("The Confusion Matrix is -")
print(confusion_matrix(y_test,Y_pred))
print("The Classification Report Matrix is -")
print(classification_report(y_test,Y_pred))

The Confusion Matrix is -
[[130   0]
 [ 75   0]]
The Classification Report Matrix is -
              precision    recall  f1-score   support

           0       0.63      1.00      0.78       130
           1       0.00      0.00      0.00        75

    accuracy                           0.63       205
   macro avg       0.32      0.50      0.39       205
weighted avg       0.40      0.63      0.49       205



/Users/naveenrenji/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naveenrenji/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naveenrenji/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Multinomial Naive Bayes

In [11]:
nbm = MultinomialNB()
nbm.fit(X_train, y_train)
nbm.score(X_test, y_test)
Y_pred=nbm.predict(X_test)
print("The Confusion Matrix is -")
print(confusion_matrix(y_test,Y_pred))
print("The Classification Report Matrix is -")
print(classification_report(y_test,Y_pred))

The Confusion Matrix is -
[[126   4]
 [ 15  60]]
The Classification Report Matrix is -
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       130
           1       0.94      0.80      0.86        75

    accuracy                           0.91       205
   macro avg       0.92      0.88      0.90       205
weighted avg       0.91      0.91      0.91       205

